# DataSource
spring:
  datasource:
    url: jdbc:postgresql://dpg-cmucn3nqd2ns738i5t60-a.singapore-postgres.render.com:5432/employees_692r
    username: tsudatomoki
    password: mL9qq1TPdlUSoewoRDpBz0EOxJz5QxKq
    sql:
      init:
        mode: always
    init:
      encoding: utf-8
    driver-class-name: org.postgresql.Driver
