spring:
  datasource:
    url: ${EMPLOYEE_DB_URL:jdbc:postgresql://localhost:5432/sample}
    username: ${EMPLOYEE_DB_USER:user}
    password: ${EMPLOYEE_DB_PASS_WORD:password}
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 2
      maximum-pool-size: 5
  flyway:
    enabled: true

mybatis:
  configuration:
    map-underscore-to-camel-case: true
